version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5673:5672"    # ATENÇÃO: Estás a mapear para 5673 na máquina, mas o container vai continuar 5672
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  tracking-service:
    build: .
    container_name: "tracking-service"
    depends_on:
      - rabbitmq
    ports:
      - "5007:5007"
    restart: always
    environment:
      RABBITMQ_HOST: "rabbitmq"
